version: '3'

# NOTE: You must set the PLOS_THEMES_REPO environment variables as well as all
#       environment variables not explicitly defined below (e.g. CAS_URL)

services:

  wombat:
    image: plos/wombat:latest
    depends_on:
      - db
      - rhino
    environment:
      - CAS_URL
      - NED_URL
      - SOLR_URL
      - DEBUG
      - LOG_LEVEL
      - RHINO_URL=${RHINO_URL:-http://rhino:8080/v2/}
      - THEME_PATH=/opt/plos/themes
      - COLLECTIONS_URL
      - MEMCACHED_SERVER=memcached:11211
    links:
      - db
      - rhino
      - memcached
    expose:
      - 8080
    volumes:
      - ${PLOS_THEMES_REPO}:/opt/plos/themes:ro

  rhino:
    image: plos/rhino:latest
    depends_on:
      - db
    environment:
      - CONTENT_REPO_URL
      - CORPUS_BUCKET
      - TAXONOMY_URL
      - THESAURUS
      - DATABASE_URL=jdbc:mysql://db:3306/ambra?user=root&password=password
    links:
      - db
    ports:
      - 8006:8080

  db:
    image: mysql:5.7.29
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: ambra

  memcached:
    image: memcached:latest

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - wombat
    ports:
      - "8080:8080"
