# Copyright (c) 2017 Public Library of Science
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.

# Overrides of this file change the Spring request mappings from their default values. That is,
# you can customize the way that URLs map to particular controller methods for each theme. You can
# also disable controller methods for a theme,
#
# Each dictionary key is the `name` value of a `@RequestMapping` annotation on a controller
# method. (This allows you to override individual controller methods in subthemes, as with any
# other dictionary key in config files like this one.) The value of each entry describes the
# custom request mapping that replaces the mapping from the webapp.
#
# For example, request mappings that look like this in the webapp's source code:
#
#     @RequestMapping(name = "articleAuthors", value = "/article/authors")
#     public String renderArticleAuthors(...)
#
#     @RequestMapping(name = "articleCommentTree", value = "/article/comment")
#     public String renderArticleCommentTree(...)
#
# could be customized by a config file that looks like this:
#
#     {
#       "articleAuthors": {
#         "pattern": "/a/auth"
#       },
#       "articleCommentTree": {
#         "disabled": true
#       }
#     }
#
# There are two keys that may appear in the value.
#
# * `pattern`: A mapping pattern that directly replaces the `value` attribute of the
#   `@RequestMapping` annotation. If omitted, use the default that is defined by the webapp.
#
# * `disabled`: A boolean value indicating whether the mapped page should show up in this theme at
#   all. If it is `true`, requests that would otherwise be mapped to the controller will go to a
#   404 page instead. If null or omitted, defaults to `false`.
#
# Note that, if `disabled` is `true`, the pattern will be ignored. So config values will generally
# have either a `pattern` value or `"disabled": true`, never both. (We could have accomplished the
# same thing by having a null pattern mean "disabled", but this way gives us the flexibility to
# add more values in the future.)

{
  "browse": {
    "disabled": true
  },

  "browseSubjectArea": {
    "disabled": true
  }
}
