#!/usr/bin/env bash
# set -x
set -e

case "$1" in
  configure|reconfigure)

    . /usr/share/debconf/confmodule

    INPUT="db_input high [[artifactId]]"

########### BEGIN app-specific code ###########

# parameters provided by the debconf wizard
$INPUT/wombat_port || true

########### END app-specific code ###########

    db_go || true

  ;;

  abort-upgrade)
  ;;

  *)
      echo "config called with unknown argument \`$1'" >&2
      exit 1
  ;;
esac

