#!/usr/bin/env bash

set -e

NAME=wombat

TOMCAT7_USER=$NAME
TOMCAT7_GROUP=$NAME
HOME=/opt/plos/$NAME
CONFFILE=/etc/default/$NAME

# In case this system is running systemd, we make systemd reload the unit files
# to pick up changes.
if [ -d /run/systemd/system ] ; then
  systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section


case "$1" in
  remove)
    # TODO: dont remove configs?
  ;;

  purge)
    # ignore errors during purge
    set +e

    . /usr/share/debconf/confmodule
    db_purge

    rm -rf $HOME
    rm -f $CONFFILE

    deluser $TOMCAT7_USER
    delgroup $TOMCAT7_GROUP

    set -e
  ;;

  upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    # Nothing to do here
  ;;

  *)
    echo "$0 called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac
