#!/usr/bin/env bash
#set -x
set -o errexit

. /usr/share/debconf/confmodule

NAME=wombat

TOMCAT7_USER=$NAME
TOMCAT7_GROUP=$NAME
HOME=/opt/plos/$NAME

function process_env_template {
	CONTEXT_TEMPLATE=$1
	OUTFILE=$2

  ls -lh $CONTEXT_TEMPLATE

	echo "Processing template $CONTEXT_TEMPLATE"

  eval "cat <<EOF
$(<$CONTEXT_TEMPLATE)
EOF
" > $OUTFILE
}

case "$1" in
  configure|reconfigure)

  # create user/group

	if ! getent group "$TOMCAT7_GROUP" > /dev/null 2>&1 ; then
	    addgroup --system "$TOMCAT7_GROUP" --quiet
	fi
	if ! id $TOMCAT7_USER > /dev/null 2>&1 ; then
	    adduser --system --home $HOME --no-create-home \
		--ingroup "$TOMCAT7_GROUP" --disabled-password --shell /bin/false \
		"$TOMCAT7_USER"
	fi

	chmod +x $HOME/bin/*.sh
	chown -Rh $TOMCAT7_USER:$TOMCAT7_GROUP $HOME

	echo "Fetching configuration from debconf"
	GET="db_get [[artifactId]]"

########### BEGIN app-specific code ###########

  # Fetching configuration from debconf

  $GET/wombat_port && export WOMBAT_PORT=$RET
  $GET/control_port && export CONTROL_PORT=$RET
  $GET/tomcat_admin_user && export TOMCAT_ADMIN_USER=$RET
  $GET/tomcat_admin_password && export TOMCAT_ADMIN_PASSWORD=$RET

########### END app-specific code ###########

	echo "Running db_purge"
	db_purge

	process_env_template $HOME/conf/context.template.xml $HOME/conf/context.xml

	process_env_template $HOME/conf/server.template.xml $HOME/conf/server.xml

	process_env_template $HOME/bin/setenv.template.sh $HOME/bin/setenv.sh

  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

service [[artifactId]] stop || true
