This page has moved. Please click <a href="<@siteLink path='${defaultTarget}'/>">here</a> if you are not redirected automatically.

<script type="text/javascript">
    var redirects = {
        'eic#grant': 's/editors-in-chief#loc-grant-mcfadden',
        'eic#pbourne': 's/editors-in-chief#loc-philip-e-bourne',
        'eic#rnussinov': 's/editors-in-chief#loc-ruth-nussinov',
        'eic': 's/editors-in-chief',
        'figureGuidelines#ccal': 's/figures#loc-content-license',
        'figureGuidelines#policies ': 's/figures#loc-policies',
        'figureGuidelines#supportinginformation': 's/figures#loc-supporting-information-si-figures',
        'figureGuidelines#tables': 's/tables',
        'figureGuidelines': 's/figures',
        'figureInstructions#convertingfigs': 's/figures#loc-converting-files-to-tiff-or-eps',
        'figureInstructions#step2eps': 's/figures#loc-converting-files-to-tiff-or-eps',
        'figureInstructions#step2tiff': 's/figures#loc-converting-files-to-tiff-or-eps',
        'figureInstructions#step1': 's/figures#loc-converting-files-to-tiff-or-eps',
        'figureInstructions#microsoftoffice': 's/figures#loc-figures-created-in-microsoft-office',
        'figureInstructions#othersoftware': 's/figures#loc-other-software',
        'figureInstructions': 's/figures',
        'figuresfaq#faq12 ': 's/supporting-information',
        'figuresfaq#faq9 ': 's/tables',
        'figuresfaq': 's/figures',
        'figureSpecifications#captions': 's/figures#loc-captions',
        'figureSpecifications#captionscitations': 's/figures#loc-in-text-citations',
        'figureSpecifications#colormode': 's/figures#loc-file-requirements',
        'figureSpecifications#dimensions': 's/figures#loc-file-requirements',
        'figureSpecifications#fileformat ': 's/figures#loc-file-requirements',
        'figureSpecifications#filesize': 's/figures#loc-file-requirements',
        'figureSpecifications#flattenedtiffs': 's/figures#loc-file-requirements',
        'figureSpecifications#general': 's/figures#loc-file-requirements',
        'figureSpecifications#latexfigures': 's/figures#loc-file-requirements',
        'figureSpecifications#linesrulesstrokes': 's/figures#loc-file-requirements',
        'figureSpecifications#orientation': 's/figures#loc-file-requirements',
        'figureSpecifications#resolution': 's/figures#loc-file-requirements',
        'figureSpecifications#stereograms': 's/figures#loc-file-requirements',
        'figureSpecifications#textinfigures': 's/figures#loc-file-requirements',
        'figureSpecifications#whitespace': 's/figures#loc-file-requirements',
        'guidelines#abbreviations': 's/submission-guidelines#loc-abbreviations',
        'guidelines#abstract': 's/submission-guidelines#loc-abstract',
        'guidelines#accession': 's/submission-guidelines#loc-accession-numbers',
        'guidelines#acks': 's/submission-guidelines#loc-acknowledgments',
        'guidelines#animal': 's/submission-guidelines#loc-animal-research',
        'guidelines#antibodies': 's/submission-guidelines#loc-antibodies',
        'guidelines#appeals': 's/editorial-and-peer-review-process#loc-appeals',
        'guidelines#articlefile': 's/submission-guidelines#loc-style-and-format',
        'guidelines#authorsummary': 's/submission-guidelines#loc-author-summary',
        'guidelines#authors': 's/submission-guidelines#loc-author-list',
        'guidelines#blotsandgels': 's/submission-guidelines#loc-blots-and-gels',
        'guidelines#botanical': 's/submission-guidelines#loc-new-taxon-names',
        'guidelines#cell': 's/submission-guidelines#loc-cell-lines',
        'guidelines#clinical': 's/submission-guidelines#loc-clinical-trials',
        'guidelines#competing': 's/submission-guidelines#loc-competing-interests',
        'guidelines#coverletter': 's/submission-guidelines#loc-cover-letter',
        'guidelines#criteria': 's/editorial-and-peer-review-process#loc-criteria-for-publication',
        'guidelines#database': 's/submission-guidelines#loc-methods-software-database-and-tools',
        'guidelines#datareporting': 's/submission-guidelines#loc-data-reporting',
        'guidelines#ed_decisions': 's/editorial-and-peer-review-process',
        'guidelines#editorial': 's/editorial-and-peer-review-process',
        'guidelines#electronicformats': 's/submission-guidelines#loc-style-and-format',
        'guidelines#embargoes': 's/press-and-media',
        'guidelines#fig': 's/submission-guidelines#loc-figures-and-tables',
        'guidelines#financialdisclosure': 's/submission-guidelines#loc-funding-statement',
        'guidelines#format': 's/submission-guidelines#loc-style-and-format',
        'guidelines#fungal': 's/submission-guidelines#loc-new-taxon-names',
        'guidelines#guidelines': 's/submission-guidelines#loc-manuscript-organization',
        'guidelines#human': 's/submission-guidelines#loc-human-and-animal-research',
        'guidelines#intro': 's/submission-guidelines#loc-introduction',
        'guidelines#latex': 's/latex',
        'guidelines#materials': 's/submission-guidelines#loc-materials-and-methods',
        'guidelines#multimedia': 's/submission-guidelines#loc-supporting-information',
        'guidelines#nomenclature': 's/submission-guidelines#loc-nomenclature',
        'guidelines#observational': 's/submission-guidelines#loc-observational-and-field-studies',
        'guidelines#open': 's/content-license',
        'guidelines#organization': 's/submission-guidelines#loc-manuscript-organization',
        'guidelines#other': 's/other-article-types',
        'guidelines#outline': 's/accepted-manuscripts',
        'guidelines#overview': 's/editorial-and-peer-review-process',
        'guidelines#paleontology': 's/submission-guidelines#loc-paleontology-and-archaeology-research',
        'guidelines#peerreview': 's/editorial-and-peer-review-process',
        'guidelines#preparation': 's/submission-guidelines',
        'guidelines#presubmission': 's/presubmission-inquiries',
        'guidelines#presubs': 's/presubmission-inquiries ',
        'guidelines#prior': 's/submission-guidelines#loc-related-manuscripts',
        'guidelines#privacy': 's/submission-guidelines#loc-human-and-animal-research',
        'guidelines#production': 's/accepted-manuscripts',
        'guidelines#publication': 's/publication-fees',
        'guidelines#qualitative': 's/submission-guidelines#loc-qualitative-research',
        'guidelines#readerresponses': 's/comments',
        'guidelines#ready': 's/submit-now',
        'guidelines#references': 's/submission-guidelines#loc-references',
        'guidelines#results': 's/submission-guidelines#loc-results-discussion-conclusions',
        'guidelines#reviews': 's/other-article-types#loc-reviews',
        'guidelines#rri': 's/submission-guidelines#loc-research-resource-identifiers',
        'guidelines#software': 's/submission-guidelines#loc-software-submissions',
        'guidelines#specific': 's/submission-guidelines#loc-guidelines-for-specific-study-types',
        'guidelines#specific': 's/submission-guidelines#loc-guidelines-for-specific-study-types',
        'guidelines#status': 's/submission-guidelines#loc-author-list',
        'guidelines#striking': 's/submission-guidelines#loc-striking-image',
        'guidelines#supporting': 's/submission-guidelines#loc-supporting-information',
        'guidelines#systematic': 's/submission-guidelines#loc-systematic-reviews-and-meta-analyses',
        'guidelines#tables': 's/submission-guidelines#loc-figures-and-tables',
        'guidelines#title': 's/submission-guidelines#loc-title',
        'guidelines#viewpoints': 's/other-article-types#loc-viewpoints',
        'guidelines#zoological': 's/submission-guidelines#loc-new-taxon-names',
        'guidelines': 's/submission-guidelines',
        'policies#animal': 's/animal-research',
        'policies#author': 's/ethical-publishing-practice#loc-authorship',
        'policies#blogs': 's/press-and-media',
        'policies#competing': 's/competing-interests',
        'policies#confidentiality': 's/ethical-publishing-practice#loc-confidentiality',
        'policies#copyright': 's/content-license',
        'policies#corrections': 's/corrections-and-retractions',
        'policies#dual': 's/ethical-publishing-practice#loc-biosecurity-and-dual-use-research-of-concern',
        'policies#exclusions': 's/editorial-and-peer-review-process',
        'policies#faqs': 's/data-availability',
        'policies#funders': 's/disclosure-of-funding-sources',
        'policies#human': 's/human-subjects-research',
        'policies#journals': 's/journal-information#loc-about-plos-journals',
        'policies#misconduct': 's/ethical-publishing-practice',
        'policies#publication': 's/publication-fees',
        'policies#related': 's/ethical-publishing-practice#loc-submission-and-publication-of-related-studies',
        'policies#reporting': 's/best-practices-in-research-reporting',
        'policies#research': 's/ethical-publishing-practice#loc-research-conducted-by-plos',
        'policies#sharing': 's/materials-and-software-sharing',
        'policies#taxon': 's/best-practices-in-research-reporting',
        'policies#competing': 's/competing-interests',
        'policies': 's/editorial-and-publishing-policies',
        'publication#data%20report': 's/criteria-for-publication#loc-7',
        'publication#data%20support': 's/criteria-for-publication#loc-4',
        'publication#ethical': 's/criteria-for-publication#loc-6',
        'publication#language': 's/criteria-for-publication#loc-5',
        'publication#reporting': 's/criteria-for-publication#loc-1',
        'publication#results': 's/criteria-for-publication#loc-2 ',
        'publication#technical': 's/criteria-for-publication#loc-3 ',
        'publication': 's/criteria-for-publication',
        'reviewerGuidelines#about': 's/reviewer-guidelines',
        'reviewerGuidelines#anonymity': 's/reviewer-guidelines#loc-anonymity',
        'reviewerGuidelines#biology': 's/reviewer-guidelines#loc-transferring-reviews-to-other-journals',
        'reviewerGuidelines#competing': 's/reviewer-guidelines#loc-competing-interests',
        'reviewerGuidelines#confidentiality': 's/reviewer-guidelines#loc-confidentiality',
        'reviewerGuidelines#conflicts': 's/reviewer-guidelines#loc-competing-interests',
        'reviewerGuidelines#criteria': 's/reviewer-guidelines#loc-criteria-for-publication',
        'reviewerGuidelines#editing': 's/reviewer-guidelines',
        'reviewerGuidelines#feedback': 's/reviewer-guidelines',
        'reviewerGuidelines#fm': 's/reviewer-guidelines#loc-reviewing-pearls-review-or-opinion-submissions',
        'reviewerGuidelines#frontmatter': 's/reviewer-guidelines#loc-reviewing-viewpoints-and-review-submissions',
        'reviewerGuidelines#magazine': 's/reviewer-guidelines#loc-reviewing-magazine-submissions',
        'reviewerGuidelines#other': 's/reviewer-guidelines#loc-writing-the-review',
        'reviewerGuidelines#peer': 's/reviewer-guidelines#loc-reviewing-magazine-submissions',
        'reviewerGuidelines#process': 's/reviewer-guidelines#loc-editorial-process',
        'reviewerGuidelines#review': 's/reviewer-guidelines#loc-editorial-process',
        'reviewerGuidelines#selection': 's/reviewer-guidelines#loc-editorial-process',
        'reviewerGuidelines#sharing': 's/reviewer-guidelines#loc-transferring-reviews-to-other-journals',
        'reviewerGuidelines#timely': 's/reviewer-guidelines#loc-timing',
        'reviewerGuidelines#writing': 's/reviewer-guidelines#loc-writing-the-review',
        'reviewerGuidelines': 's/reviewer-guidelines',
        'tableSpecifications#dosdonts': 's/tables#loc-examples',
        'tableSpecifications#intexttablecitations': 's/tables#loc-in-text-citations',
        'tableSpecifications#requirements': 's/tables#loc-requirements ',
        'tableSpecifications#tablecaptions': 's/tables#loc-captions-legends-footnotes',
        'tableSpecifications': 's/tables '
    };

    var journal_redirects = {
        'PLoSONE': {
            'editorial#animal': 's/animal-research',
            'editorial#authorship': 's/ethical-publishing-practice#loc-authorship',
            'editorial#clinical': 's/human-subjects-research#loc-clinical-trials',
            'editorial#competing': 's/competing-interests',
            'editorial#copyright': 's/content-license',
            'editorial#disputing': 's/submission-guidelines#loc-manuscripts-disputing-published-work',
            'editorial#dual': 's/ethical-publishing-practice#loc-biosecurity-and-dual-use-research-of-concern',
            'editorial#ethics': 's/ethical-publishing-practice',
            'editorial#fees': 's/publication-fees',
            'editorial#funding': 's/disclosure-of-funding-sources',
            'editorial#human': 's/human-subjects-research',
            'editorial#image': 's/ethical-publishing-practice',
            'editorial#methods': 's/submission-guidelines#loc-methods-software-database-and-tools',
            'editorial#overview': 's/editorial-and-peer-review-process',
            'editorial#paleontology': 's/submission-guidelines#loc-paleontology-and-archaeology-research',
            'editorial#peer': 's/editorial-and-peer-review-process',
            'editorial#plagiarism': 's/ethical-publishing-practice',
            'editorial#policies': 's/editorial-and-publishing-policies',
            'editorial#related': 's/ethical-publishing-practice#loc-submission-and-publication-of-related-studies',
            'editorial#sharing': 's/data-availability',
            'editorial': 's/editorial-and-publishing-policies',
            'guidelines#criteria': 's/criteria-for-publication',
            'guidelines#human': 's/submission-guidelines#loc-human-subjects-research',
            'guidelines#software': 's/submission-guidelines#loc-methods-software-database-and-tools',
            'policies#taxon': 's/submission-guidelines#loc-new-taxon-names'
        },
        'PLoSMedicine': {
            'editorsInterests#aross': 's/competing-interests-of-the-plos-medicine-editors#loc-amy-ross',
            'editorsInterests#lpeiperl': 's/competing-interests-of-the-plos-medicine-editors#loc-larry-peiperl',
            'editorsInterests#psimpson': 's/competing-interests-of-the-plos-medicine-editors#loc-paul-simpson',
            'editorsInterests#rmacdonald': 's/competing-interests-of-the-plos-medicine-editors#loc-rhona-macdonald',
            'editorsInterests#tmcbride': 's/competing-interests-of-the-plos-medicine-editors#loc-thomas-mcbride',
            'editorsInterests': 's/competing-interests-of-the-plos-medicine-editors',
            'guidelines#supporting': 's/submission-guidelines#loc-additional-information-requested-at-submission'
        }
    };

    // override with any journal-specific redirects
    if ("${journalKey}" in journal_redirects) {
        for (var key in journal_redirects["${journalKey}"]) {
            redirects[key] = journal_redirects["${journalKey}"][key];
        }
    }

    var current_anchor = window.location.hash;
    var target = "${defaultTarget}";
    for (var anchor_regex in redirects) {
        if (RegExp(anchor_regex).test("${sourcePage}" + current_anchor)) {
            target = redirects[anchor_regex];
            break;
        }
    }

    window.location.replace("<@siteLink path='" + target + "'/>");

</script>