apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: "wombat"
  app.kubernetes.io/part-of: "journals"
  app.kubernetes.io/component: "frontend"
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
configMapGenerator:
- name: wombat-configmap
  envs:
    - config.env